export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  TASK_LIMIT_EXCEEDED: "TASK_LIMIT_EXCEEDED",
  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
  DELINQUENT_ACCOUNT: "DELINQUENT_ACCOUNT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  SECRET_ENCRYPTION_CONFIG_INVALID: "SECRET_ENCRYPTION_CONFIG_INVALID",
  SECRET_DECRYPTION_FAILED: "SECRET_DECRYPTION_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
