import type { JobDefinition } from "cronlet";

export interface RouteGeneratorOptions {
  /** Relative import path to the job file */
  importPath: string;
  /** Whether to generate TypeScript */
  typescript: boolean;
  /** Max function duration in seconds */
  maxDuration?: number;
}

/**
 * Generate an App Router route handler for a job
 */
export function generateAppRoute(
  job: JobDefinition,
  options: RouteGeneratorOptions
): string {
  const { importPath, typescript, maxDuration } = options;

  // Calculate max duration from job timeout or use provided value
  let duration = maxDuration ?? 60;
  if (job.config.timeout) {
    const match = job.config.timeout.match(/^(\d+)(s|m|h)$/);
    if (match) {
      const value = parseInt(match[1]!, 10);
      const unit = match[2]!;
      switch (unit) {
        case "s":
          duration = value;
          break;
        case "m":
          duration = value * 60;
          break;
        case "h":
          duration = value * 3600;
          break;
      }
    }
  }

  // Cap at reasonable max (300s = 5 minutes, Vercel Pro limit)
  duration = Math.min(duration, 300);

  const typeAnnotations = typescript
    ? `
import type { NextRequest } from "next/server";`
    : "";

  const requestType = typescript ? "NextRequest" : "Request";

  return `// Generated by cronlet — do not edit

/**
 * Job: ${job.id}
 * Schedule: ${job.schedule.humanReadable}
 * Cron: ${job.schedule.cron}
 */${typeAnnotations}
import { verifyCronRequest, executeJob } from "cronlet/verify";
import job from "${importPath}";

export const runtime = "nodejs";
export const maxDuration = ${duration};

// Vercel Cron sends GET requests to trigger jobs
export async function GET(request${typescript ? `: ${requestType}` : ""}) {
  // Verify request is from Vercel Cron
  const verification = verifyCronRequest(request);
  if (!verification.ok) {
    return new Response(JSON.stringify({ error: verification.error }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Execute the job
  const result = await executeJob(job);

  if (result.status === "success") {
    return new Response(JSON.stringify({
      jobId: "${job.id}",
      runId: result.runId,
      duration: result.duration,
      status: "success",
    }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Return 500 so Vercel logs it as failed
  return new Response(JSON.stringify({
    jobId: "${job.id}",
    runId: result.runId,
    status: result.status,
    error: result.error?.message,
    attempt: result.attempt,
  }), {
    status: 500,
    headers: { "Content-Type": "application/json" },
  });
}
`;
}
