import type { JobDefinition } from "cronlet";

export interface RouteGeneratorOptions {
  /** Relative import path to the job file */
  importPath: string;
  /** Whether to generate TypeScript */
  typescript: boolean;
  /** Max function duration in seconds */
  maxDuration?: number;
}

/**
 * Generate a Pages Router API route for a job
 */
export function generatePagesRoute(
  job: JobDefinition,
  options: RouteGeneratorOptions
): string {
  const { importPath, typescript, maxDuration } = options;

  // Calculate max duration from job timeout or use provided value
  let duration = maxDuration ?? 60;
  if (job.config.timeout) {
    const match = job.config.timeout.match(/^(\d+)(s|m|h)$/);
    if (match) {
      const value = parseInt(match[1]!, 10);
      const unit = match[2]!;
      switch (unit) {
        case "s":
          duration = value;
          break;
        case "m":
          duration = value * 60;
          break;
        case "h":
          duration = value * 3600;
          break;
      }
    }
  }

  // Cap at reasonable max (300s = 5 minutes, Vercel Pro limit)
  duration = Math.min(duration, 300);

  const typeImport = typescript
    ? `import type { NextApiRequest, NextApiResponse } from "next";
`
    : "";

  const paramTypes = typescript
    ? `(req: NextApiRequest, res: NextApiResponse)`
    : "(req, res)";

  return `// Generated by cronlet — do not edit

/**
 * Job: ${job.id}
 * Schedule: ${job.schedule.humanReadable}
 * Cron: ${job.schedule.cron}
 */
${typeImport}import { verifyCronRequest, executeJob } from "cronlet/verify";
import job from "${importPath}";

export const config = {
  maxDuration: ${duration},
};

// Vercel Cron sends GET requests to trigger jobs
export default async function handler${paramTypes} {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Verify request is from Vercel Cron
  const verification = verifyCronRequest(req);
  if (!verification.ok) {
    return res.status(401).json({ error: verification.error });
  }

  // Execute the job
  const result = await executeJob(job);

  if (result.status === "success") {
    return res.status(200).json({
      jobId: "${job.id}",
      runId: result.runId,
      duration: result.duration,
      status: "success",
    });
  }

  // Return 500 so Vercel logs it as failed
  return res.status(500).json({
    jobId: "${job.id}",
    runId: result.runId,
    status: result.status,
    error: result.error?.message,
    attempt: result.attempt,
  });
}
`;
}
